import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Siddhesh Lakhani",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await new Promise((resolve) => setTimeout(resolve, 2000));
  return (
    <html lang="en">
      <body className={`${inter.className}`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
